databases:
  - name: Correos_db
    databaseName: Correos_db
    user: correos_db_user

services:
  - type: web
    name: Correos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Correos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Correos_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4