databases:
  - name: Correos
    databaseName: Correos
    user: Correos

services:
  - type: web
    name: Correos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Correos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Correos
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4