databases:
  - name: Correos
    databaseName: correos_db_v2
    user: correos_db_user

services:
  - type: web
    name: correos_db_v2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Correos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: correos_db_v2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4