# Generated by Django 4.2.8 on 2023-12-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMembers',
        ),
    ]
