# Generated by Django 4.2.8 on 2023-12-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='agent_photos/', verbose_name='Profile Picture'),
        ),
    ]
