# Generated by Django 4.2.8 on 2023-12-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_alter_teammembers_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='picture',
        ),
    ]
