# Generated by Django 4.2.8 on 2024-03-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undercontractbuyer',
            name='buyer_email',
            field=models.CharField(max_length=100, verbose_name="Buyer's Email"),
        ),
    ]
